services:
  db:
    image: "postgres:15"
    container_name: db
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  app:
    build:
      context: ./
    container_name: quarterly-rep-backend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${PORT}:${PORT}
    working_dir: /app
    depends_on:
      - db
    env_file:
      - .env
    expose:
      - ${PORT}
