services:
  app:
    build:
      context: ./
    container_name: quarterly-rep-backend
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    working_dir: /app
    depends_on:
      - db
      - minio
    env_file:
      - .env
    expose:
      - 3000
