services:
  db:
    image: "postgres:15"
    container_name: db
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  minio:
    image: "minio/minio:RELEASE.2024-02-17T01-15-57Z"
    container_name: minio
    restart: always
    command: server --console-address ":9090" /data
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_PASSWORD}
    volumes:
      - ./minio-data:/data

  app:
    build:
      context: ./
    container_name: quarterly-rep-backend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${PORT}:${PORT}
    working_dir: /app
    depends_on:
      - db
      - minio
    env_file:
      - .env
    expose:
      - ${PORT}
